sudo: required
services: 
    -docker

before_install:
    - docker build -t ntambellini/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true USERNAME/react-test npm test

after_success:
    - docker build -t ntambellini/multi-client ./client
    - docker build -t ntambellini/multi-nginix ./nginix
    - docker build -t ntambellini/multi-server ./server
    - docker build -t ntambellini/multi-worker ./worker

# Log into the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Push the images to docker hub
    - docker push ntambellini/multi-client
    - docker push ntambellini/multi-nginix
    - docker push ntambellini/multi-server
    - docker push ntambellini/multi-worker